# Generated by Django 6.0.7 on 2026-07-16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('topic', models.TextField()),
                ('target_audience', models.CharField(blank=True, max_length=255)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mixed', 'Mixed level')], default='beginner', max_length=20)),
                ('language', models.CharField(default='en', max_length=20)),
                ('delivery_mode', models.CharField(choices=[('instructor_led', 'Instructor-led'), ('self_paced', 'Self-paced'), ('workshop', 'Workshop')], default='instructor_led', max_length=20)),
                ('desired_duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('learning_outcomes', models.JSONField(blank=True, default=list)),
                ('prerequisites', models.TextField(blank=True)),
                ('required_tools', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('author_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('ready_for_review', 'Ready for review'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.CreateModel(
            name='CurriculumVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('course_description', models.TextField(blank=True)),
                ('suggested_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('revision_instruction', models.TextField(blank=True)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_versions', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_curriculum_versions', to=settings.AUTH_USER_MODEL)),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='courses.curriculumversion')),
            ],
            options={'ordering': ('-version_number',)},
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('learning_outcomes', models.JSONField(blank=True, default=list)),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('curriculum_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.curriculumversion')),
            ],
            options={'ordering': ('position', 'pk')},
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('outline', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued for generation'), ('generating', 'Generating'), ('ready', 'Ready for review'), ('approved', 'Approved'), ('failed', 'Generation failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursesection')),
            ],
            options={'ordering': ('position', 'pk')},
        ),
        migrations.CreateModel(
            name='LessonRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('revision_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('content_markdown', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_lesson_revisions', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='courses.lesson')),
            ],
            options={'ordering': ('-revision_number',)},
        ),
        migrations.CreateModel(
            name='CourseProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('evaluation_criteria', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_project', to='courses.curriculumversion')),
            ],
            options={'verbose_name': 'course project', 'verbose_name_plural': 'course projects'},
        ),
        migrations.AddConstraint(
            model_name='curriculumversion',
            constraint=models.UniqueConstraint(fields=('course', 'version_number'), name='unique_curriculum_version_number_per_course'),
        ),
        migrations.AddConstraint(
            model_name='curriculumversion',
            constraint=models.UniqueConstraint(condition=Q(('status', 'approved')), fields=('course',), name='one_approved_curriculum_per_course'),
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.UniqueConstraint(fields=('curriculum_version', 'position'), name='unique_section_position_per_curriculum'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('section', 'position'), name='unique_lesson_position_per_section'),
        ),
        migrations.AddConstraint(
            model_name='lessonrevision',
            constraint=models.UniqueConstraint(fields=('lesson', 'revision_number'), name='unique_lesson_revision_number'),
        ),
    ]
