# Generated by Django 6.0 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumversion',
            name='calculated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='duration_estimate_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='overall_learning_outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
    ]
