# Generated by Django 6.0.7 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_curriculum_planning_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='starting_level',
            field=models.CharField(
                blank=True,
                choices=[
                    ('beginner', 'Beginner'),
                    ('intermediate', 'Intermediate'),
                    ('advanced', 'Advanced'),
                    ('mixed', 'Mixed level'),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='target_completion_level',
            field=models.CharField(
                blank=True,
                choices=[
                    ('beginner', 'Beginner'),
                    ('intermediate', 'Intermediate'),
                    ('advanced', 'Advanced'),
                    ('mixed', 'Mixed level'),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
