# Generated by Django 6.0.7 on 2026-07-16

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('adapter_type', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google_genai', 'Google GenAI'), ('openai_compatible', 'OpenAI-compatible')], max_length=30)),
                ('api_key_environment_variable', models.CharField(max_length=100)),
                ('base_url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ('display_order', 'name')},
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identifier', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('default_temperature', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('default_max_output_tokens', models.PositiveIntegerField(default=4000, validators=[django.core.validators.MinValueValidator(1)])),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='generation.llmprovider')),
            ],
            options={'ordering': ('provider__display_order', 'display_order', 'identifier')},
        ),
        migrations.CreateModel(
            name='GenerationSettings',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('default_temperature', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('max_output_tokens', models.PositiveIntegerField(default=4000, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_continuations', models.PositiveSmallIntegerField(default=3)),
                ('request_timeout_seconds', models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('daily_cost_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_generation_settings', to='generation.llmmodel')),
                ('default_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_generation_settings', to='generation.llmprovider')),
            ],
            options={'verbose_name': 'generation settings', 'verbose_name_plural': 'generation settings'},
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job_type', models.CharField(choices=[('curriculum', 'Curriculum'), ('lesson', 'Lesson')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('retrying', 'Retrying'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('needs_review', 'Needs review')], default='queued', max_length=20)),
                ('input_metadata', models.JSONField(blank=True, default=dict)),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='courses.course')),
                ('curriculum_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='courses.curriculumversion')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='courses.lesson')),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_jobs', to='generation.llmmodel')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_jobs', to='generation.llmprovider')),
            ],
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='GenerationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attempt_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='started', max_length=20)),
                ('prompt_template_version', models.CharField(max_length=100)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('response_metadata', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='generation.generationjob')),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_attempts', to='generation.llmmodel')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_attempts', to='generation.llmprovider')),
            ],
            options={'ordering': ('-attempt_number',)},
        ),
        migrations.AddConstraint(
            model_name='llmmodel',
            constraint=models.UniqueConstraint(fields=('provider', 'identifier'), name='unique_llm_model_identifier_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='generationattempt',
            constraint=models.UniqueConstraint(fields=('job', 'attempt_number'), name='unique_generation_attempt_number_per_job'),
        ),
    ]
