# Generated by Django 6.0.7 on 2026-07-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_curriculum_planning_details'),
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='generationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('job_type', 'lesson'), ('status__in', ('queued', 'running', 'retrying'))), fields=('lesson',), name='unique_active_lesson_generation_job'),
        ),
    ]
