# Generated by Django 6.0.7 on 2026-07-17 12:16

from django.db import migrations, models

BIBLE_PROVIDER_CATALOG = [
    (
        'Open AI',
        'OpenAI models for general-purpose text generation.',
        'openai',
        'OPENAI_API_KEY',
        '',
        1,
        [
            ('gpt-4o-mini', 'Fast, affordable OpenAI model for focused tasks.', 1),
            ('gpt-4o', 'Fast, intelligent, flexible OpenAI model.', 2),
            ('gpt-5-mini', 'Cost-efficient GPT-5 model for well-defined tasks.', 3),
            ('gpt-5.2', 'Frontier OpenAI model for advanced reasoning and generation.', 4),
        ],
    ),
    (
        'Anthropic',
        'Claude models from Anthropic.',
        'anthropic',
        'ANTHROPIC_API_KEY',
        '',
        2,
        [
            ('claude-3-5-haiku-20241022', 'Fast Claude Haiku model.', 1),
            ('claude-sonnet-4-20250514', 'High-performance Claude Sonnet model.', 2),
            ('claude-opus-4-1-20250805', 'Most capable Claude Opus 4.1 model.', 3),
        ],
    ),
    (
        'Google',
        'Gemini models from Google AI.',
        'google_genai',
        'GOOGLE_API_KEY',
        '',
        3,
        [
            ('gemini-2.5-flash', 'Fast Gemini 2.5 model for low-latency work.', 1),
            ('gemini-2.5-flash-lite', 'Most cost-efficient Gemini 2.5 Flash variant.', 2),
            ('gemini-2.5-pro', 'Advanced Gemini 2.5 model for complex tasks.', 3),
        ],
    ),
    (
        'DeepSeek',
        'DeepSeek OpenAI-compatible chat models.',
        'openai_compatible',
        'DEEPSEEK_API_KEY',
        'https://api.deepseek.com',
        4,
        [
            ('deepseek-chat', 'DeepSeek general chat model.', 1),
            ('deepseek-reasoner', 'DeepSeek reasoning model.', 2),
            ('deepseek-v4-pro', 'DeepSeek V4 Pro model.', 3),
        ],
    ),
    (
        'Groq',
        'Groq-hosted chat models.',
        'openai_compatible',
        'GROQ_API_KEY',
        'https://api.groq.com/openai/v1',
        5,
        [
            ('llama-3.3-70b-versatile', 'Groq-hosted Llama 3.3 70B model.', 1),
            ('openai/gpt-oss-120b', 'Groq-hosted OpenAI GPT OSS 120B model.', 2),
            ('llama-3.1-8b-instant', 'Groq-hosted low-latency Llama 3.1 8B model.', 3),
        ],
    ),
]


def seed_bible_provider_catalog(apps, schema_editor):
    LLMProvider = apps.get_model('generation', 'LLMProvider')
    LLMModel = apps.get_model('generation', 'LLMModel')
    for name, description, adapter_type, key_name, base_url, display_order, models_data in BIBLE_PROVIDER_CATALOG:
        provider, _ = LLMProvider.objects.update_or_create(
            name=name,
            defaults={
                'description': description,
                'adapter_type': adapter_type,
                'api_key_environment_variable': key_name,
                'base_url': base_url,
                'enabled': True,
                'display_order': display_order,
            },
        )
        for identifier, model_description, model_order in models_data:
            LLMModel.objects.update_or_create(
                provider=provider,
                identifier=identifier,
                defaults={
                    'description': model_description,
                    'display_name': '',
                    'enabled': True,
                    'default_temperature': 0.7,
                    'default_max_output_tokens': 4000,
                    'display_order': model_order,
                },
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_generationjob_unique_active_lesson_generation_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(seed_bible_provider_catalog, noop_reverse),
    ]
