# Generated by Django 6.0.7 on 2026-07-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_llmmodel_description_llmprovider_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationattempt',
            name='response_preview',
            field=models.TextField(blank=True),
        ),
    ]
