# Generated by Django 6.0.7 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0004_generationattempt_response_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationattempt',
            name='response_preview',
            field=models.TextField(blank=True, default=''),
        ),
    ]
