# Generated by Django 6.0.7 on 2026-07-19

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0005_generationattempt_response_preview_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationsettings',
            name='curriculum_response_limit',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='Leave blank to continue curriculum responses until completion, cancellation, or task timeout.',
                null=True,
                validators=[MinValueValidator(1)],
            ),
        ),
    ]
